import { useState, useEffect, useCallback } from "react";
import { getMyPayroll } from "../../services/payrollService";
import PayslipCard from "../../components/payroll/PayslipCard";
import "./MyPayslips.css";

const MONTHS = [
  "January","February","March","April","May","June",
  "July","August","September","October","November","December",
];

const fmt = (n) =>
  `₹${(n || 0).toLocaleString("en-IN", { minimumFractionDigits: 0 })}`;

const currentYear = new Date().getFullYear();
const yearOptions = Array.from({ length: 4 }, (_, i) => currentYear - i);

export default function MyPayslips() {
  const [records,   setRecords]   = useState([]);
  const [loading,   setLoading]   = useState(true);
  const [error,     setError]     = useState(null);
  const [year,      setYear]      = useState(currentYear);
  const [selected,  setSelected]  = useState(null); // payroll record for modal
  const [employee,  setEmployee]  = useState(null);

  const fetchPayroll = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await getMyPayroll(year);
      setRecords(res.data.data.records || []);
      // Employee data may be embedded — pull from first record if available
      if (res.data.data.records?.[0]?.employee) {
        setEmployee(res.data.data.records[0].employee);
      }
    } catch (err) {
      setError(err?.response?.data?.message || "Failed to load payroll records.");
    } finally {
      setLoading(false);
    }
  }, [year]);

  useEffect(() => { fetchPayroll(); }, [fetchPayroll]);

  // Summary stats for selected year
  const totalNet   = records.reduce((s, r) => s + (r.netSalary   || 0), 0);
  const totalGross = records.reduce((s, r) => s + (r.grossSalary || 0), 0);
  const totalTax   = records.reduce((s, r) => s + (r.taxDeduction || 0) + (r.pfDeduction || 0), 0);
  const paidCount  = records.filter(r => r.status === "paid").length;

  return (
    <div className="mps-page">

      {/* ── Page Header ── */}
      <div className="mps-header">
        <div>
          <h1 className="mps-header__title">My Payslips</h1>
          <p className="mps-header__sub">View and download your salary statements</p>
        </div>
        <select
          className="mps-year-select"
          value={year}
          onChange={(e) => setYear(Number(e.target.value))}
        >
          {yearOptions.map(y => (
            <option key={y} value={y}>{y}</option>
          ))}
        </select>
      </div>

      {/* ── Year Summary Cards ── */}
      {!loading && records.length > 0 && (
        <div className="mps-summary-row">
          {[
            { label: `Payslips in ${year}`, value: `${records.length} / 12`, icon: "📄" },
            { label: "Total Gross Earned",  value: fmt(totalGross),          icon: "💰" },
            { label: "Total Net Received",  value: fmt(totalNet),            icon: "💳" },
            { label: "Tax + PF Deducted",   value: fmt(totalTax),            icon: "📊" },
          ].map(({ label, value, icon }) => (
            <div key={label} className="mps-stat-card">
              <div className="mps-stat-icon">{icon}</div>
              <div className="mps-stat-val">{value}</div>
              <div className="mps-stat-lbl">{label}</div>
            </div>
          ))}
        </div>
      )}

      {/* ── States ── */}
      {loading && (
        <div className="mps-state">
          <div className="mps-spinner" />
          <p>Loading payslips...</p>
        </div>
      )}

      {error && !loading && (
        <div className="mps-state mps-state--error">
          <div className="mps-state-icon">⚠️</div>
          <p>{error}</p>
          <button className="mps-retry-btn" onClick={fetchPayroll}>Retry</button>
        </div>
      )}

      {!loading && !error && records.length === 0 && (
        <div className="mps-state">
          <div className="mps-state-icon">📭</div>
          <p>No payslips found for {year}.</p>
          <span className="mps-state-sub">Payslips are generated by HR at the end of each month.</span>
        </div>
      )}

      {/* ── Payslip List ── */}
      {!loading && !error && records.length > 0 && (
        <div className="mps-list">
          {/* Month grid — show all 12 months, grey out missing ones */}
          {MONTHS.map((monthName, idx) => {
            const monthNum = idx + 1;
            const record   = records.find(r => r.month === monthNum);

            if (!record) {
              return (
                <div key={monthName} className="mps-item mps-item--empty">
                  <div className="mps-item__month">{monthName} {year}</div>
                  <div className="mps-item__na">Not generated</div>
                </div>
              );
            }

            return (
              <div
                key={monthName}
                className="mps-item mps-item--active"
                onClick={() => setSelected(record)}
              >
                <div className="mps-item__left">
                  <div className="mps-item__month-badge">{monthName.slice(0, 3)}</div>
                  <div>
                    <div className="mps-item__month">{monthName} {year}</div>
                    <div className="mps-item__meta">
                      {record.presentDays}d present · {record.leaveDays}d leave
                      {record.absentDays > 0 && ` · ${record.absentDays}d absent`}
                    </div>
                  </div>
                </div>

                <div className="mps-item__right">
                  <div className="mps-item__amounts">
                    <div className="mps-item__net">{fmt(record.netSalary)}</div>
                    <div className="mps-item__gross">Gross {fmt(record.grossSalary)}</div>
                  </div>
                  <span className={`mps-item__badge mps-item__badge--${record.status}`}>
                    {record.status === "paid" ? "✓ Paid" : record.status === "generated" ? "Generated" : "Draft"}
                  </span>
                  <button className="mps-item__view-btn">View →</button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* ── Payslip Modal ── */}
      {selected && (
        <PayslipCard
          payroll={selected}
          employee={employee || selected.employee}
          onClose={() => setSelected(null)}
        />
      )}

    </div>
  );
}
